# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: Run Tests

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        configurations: [Release]
    runs-on: windows-latest
    env:
      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

      BUILD_PLATFORM: x64

    steps:
    - uses: actions/checkout@v2

    - name: Install ProcDump64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        curl -fsSL -o Procdump.zip https://download.sysinternals.com/files/Procdump.zip
        7z x Procdump.zip -y -o"C:/Program Files/ProcDump"
        echo "C:\Program Files\ProcDump" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        mkdir c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
        echo "test" > c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/test.txt

    - name: Set AeDebug registry key
      working-directory: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: |
        procdump64.exe -accepteula -i -r -ma c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Required, workflow file name or ID
        workflow: build.yml
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}

    - name: Run Unit Tests
      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: |
        for ($i = 0; $i -lt 100; $i++) {./unit_tests.exe -s [end_to_end]}

    - name: Check for crash dumps
      working-directory: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: if (Test-Path *.dmp) { exit 1 }

    - name: Upload any crash dumps
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Crash-Dumps-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}
        path: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
        retention-days: 5